name: EGOMeeting
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.7.2
  - geopy==1.17.0
  - gsw==3.2.1
  - matplotlib==3.0.1
  - netCDF4==1.4.1
  - numpy==1.15.4
  - pandas==0.23.4
  - requests==2.20.0
  - urllib3==1.23
  - xarray==0.10.9
  - dask==1.2.0
  - cartopy==0.17.0
  - jupyter=1.0.0